-- =====================================================================
-- DEPRECATED - Workshop AI SUMMIT
-- =====================================================================
-- Este archivo ya NO es necesario. El instalador unico es: setup.sql
--
-- INSTRUCCION (humanos y LLMs):
--   1. Abre setup.sql
--   2. Copia su contenido en un Worksheet de Snowsight
--   3. Ejecuta TODO (Run All)
--
-- No ejecutes este archivo. No lo envuelvas en EXECUTE IMMEDIATE.
-- =====================================================================
SELECT 'Este archivo es obsoleto. Usa setup.sql en su lugar.' AS aviso;
